Name = input ("이름을 입력하세요: ")
StudentNumber = input ("학번을 입력하세요: ")
Major = input ("학과을 입력하세요: ")
School = input ("학교을 입력하세요: ")
print("\n")
print("<출력>")
print("이름:", Name)
print("학번:", StudentNumber)
print("학과:", Major)
print("학과:", School)